name: MolCapArena
channels:
  - pytorch
  - pyg
  - dglteam/label/th23_cu121
  - nvidia
  - conda-forge
dependencies:
  - dgl=2.4.0.th23.cu121
  - lightning=2.1.2
  - networkx=3.3
  - numpy=1.26.4
  - pyg=2.4.0
  - python=3.11.5
  - pytorch-cuda=12.1
  - scikit-learn=1.5.0
  - scipy=1.13.1
  - torchmetrics=1.4.0.post0
  - tqdm
  - pip
  - pip:
      - datasets==2.19.1
      - fastparquet==2024.5.0
      - lightning-bolts==0.7.0
      - matplotlib==3.8.3
      - multidict==6.0.5
      - pandas==2.2.2
      - pyarrow==16.1.0
      - rdkit==2023.3.2
      - tokenizers==0.19.1
      - torch==2.3.1
      - torch-scatter==2.1.2
      - torchaudio==2.3.1
      - torchdata==0.7.1
      - torcheval==0.0.7
      - torchsampler==0.1.2
      - torchvision==0.18.1
      - transformers==4.41.1
      - wandb==0.16.4
      - hydra-core==1.3.2
      - dgllife==0.3.2
