name: Captioner
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - arrow=1.3.0=pyhd8ed1ab_0
  - python=3.11.5
  - pytorch=2.3.0
  - torchmetrics=1.4.0.post0
  - tqdm
  - pip
  - pip:
      - accelerate==0.31.0
      - datasets==2.19.1
      - flash-attn==2.5.9.post1
      - huggingface-hub==0.23.4
      - llvmlite==0.42.0
      - matplotlib==3.8.3
      - multidict==6.0.5
      - openai==1.30.5
      - pandas==2.2.2
      - peft==0.11.1
      - pyarrow==16.1.0
      - ray==2.31.0
      - rdchiral==1.1.0
      - rdkit==2023.3.2
      - scikit-learn==1.5.1
      - selfies==2.1.1
      - sentencepiece==0.2.0
      - tiktoken==0.6.0
      - tokenizers==0.19.1
      - torch==2.3.1
      - torch-cluster
      - torch-geometric==2.5.3
      - torch-scatter==2.1.2+pt23cu121
      - torch-sparse==0.6.18+pt23cu121
      - torch-spline-conv==1.2.2+pt23cu121
      - torchdata==0.7.1
      - torcheval==0.0.7
      - torchsampler==0.1.2
      - torchvision==0.18.1
      - transformers==4.43.1
      - triton==2.3.1
      - vllm==0.5.3.post1
      - vllm-flash-attn==2.5.9.post1
      - vllm-nccl-cu12==2.18.1.0.4.0
      - xformers==0.0.27
